name: Deploy Feature Branch

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Build
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build
      - name: test
        run: ls && set




